//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D3Helper.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HotkeySlot1 {
            get {
                return ((string)(this["HotkeySlot1"]));
            }
            set {
                this["HotkeySlot1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HotkeySlot2 {
            get {
                return ((string)(this["HotkeySlot2"]));
            }
            set {
                this["HotkeySlot2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HotkeySlot3 {
            get {
                return ((string)(this["HotkeySlot3"]));
            }
            set {
                this["HotkeySlot3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HotkeySlot4 {
            get {
                return ((string)(this["HotkeySlot4"]));
            }
            set {
                this["HotkeySlot4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoPotionBool {
            get {
                return ((bool)(this["AutoPotionBool"]));
            }
            set {
                this["AutoPotionBool"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double AutoPotionValue {
            get {
                return ((double)(this["AutoPotionValue"]));
            }
            set {
                this["AutoPotionValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HotkeySlotRmb {
            get {
                return ((string)(this["HotkeySlotRmb"]));
            }
            set {
                this["HotkeySlotRmb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool overlayfps {
            get {
                return ((bool)(this["overlayfps"]));
            }
            set {
                this["overlayfps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool overlayxptracker {
            get {
                return ((bool)(this["overlayxptracker"]));
            }
            set {
                this["overlayxptracker"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool overlayskillbuttons {
            get {
                return ((bool)(this["overlayskillbuttons"]));
            }
            set {
                this["overlayskillbuttons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point D3Helper_MainForm_StartPosition {
            get {
                return ((global::System.Drawing.Point)(this["D3Helper_MainForm_StartPosition"]));
            }
            set {
                this["D3Helper_MainForm_StartPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoCast1Override {
            get {
                return ((bool)(this["AutoCast1Override"]));
            }
            set {
                this["AutoCast1Override"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoCast2Override {
            get {
                return ((bool)(this["AutoCast2Override"]));
            }
            set {
                this["AutoCast2Override"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoCast3Override {
            get {
                return ((bool)(this["AutoCast3Override"]));
            }
            set {
                this["AutoCast3Override"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoCast4Override {
            get {
                return ((bool)(this["AutoCast4Override"]));
            }
            set {
                this["AutoCast4Override"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoCastRMBOverride {
            get {
                return ((bool)(this["AutoCastRMBOverride"]));
            }
            set {
                this["AutoCastRMBOverride"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoGambleBool {
            get {
                return ((bool)(this["AutoGambleBool"]));
            }
            set {
                this["AutoGambleBool"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RosBotUpgradeKadalaBool
        {
            get
            {
                return ((bool)(this["RosBotUpgradeKadalaBool"]));
            }
            set
            {
                this["RosBotUpgradeKadalaBool"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int MinDelayClick
        {
            get
            {
                return ((int)(this["MinDelayClick"]));
            }
            set
            {
                this["MinDelayClick"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public int MaxDelayClick
        {
            get
            {
                return ((int)(this["MaxDelayClick"]));
            }
            set
            {
                this["MaxDelayClick"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("175")]
        public int SleepTransmute
        {
            get
            {
                return ((int)(this["SleepTransmute"]));
            }
            set
            {
                this["SleepTransmute"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HotkeyParagonPoints1 {
            get {
                return ((string)(this["HotkeyParagonPoints1"]));
            }
            set {
                this["HotkeyParagonPoints1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HotkeyParagonPoints2 {
            get {
                return ((string)(this["HotkeyParagonPoints2"]));
            }
            set {
                this["HotkeyParagonPoints2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HotkeyParagonPoints3 {
            get {
                return ((string)(this["HotkeyParagonPoints3"]));
            }
            set {
                this["HotkeyParagonPoints3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HotkeyParagonPoints4 {
            get {
                return ((string)(this["HotkeyParagonPoints4"]));
            }
            set {
                this["HotkeyParagonPoints4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HotkeySlotLmb {
            get {
                return ((string)(this["HotkeySlotLmb"]));
            }
            set {
                this["HotkeySlotLmb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int D3Helper_UpdateRate {
            get {
                return ((int)(this["D3Helper_UpdateRate"]));
            }
            set {
                this["D3Helper_UpdateRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool overlayriftprogress {
            get {
                return ((bool)(this["overlayriftprogress"]));
            }
            set {
                this["overlayriftprogress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double riftprogress_radius {
            get {
                return ((double)(this["riftprogress_radius"]));
            }
            set {
                this["riftprogress_radius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HotkeyAutoGamble {
            get {
                return ((string)(this["HotkeyAutoGamble"]));
            }
            set {
                this["HotkeyAutoGamble"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Logger_extendedLog {
            get {
                return ((bool)(this["Logger_extendedLog"]));
            }
            set {
                this["Logger_extendedLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool overlayskillbuttonsastext {
            get {
                return ((bool)(this["overlayskillbuttonsastext"]));
            }
            set {
                this["overlayskillbuttonsastext"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool overlayconventiondraws {
            get {
                return ((bool)(this["overlayconventiondraws"]));
            }
            set {
                this["overlayconventiondraws"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Overlay_APS {
            get {
                return ((bool)(this["Overlay_APS"]));
            }
            set {
                this["Overlay_APS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HotkeyAutoPick {
            get {
                return ((string)(this["HotkeyAutoPick"]));
            }
            set {
                this["HotkeyAutoPick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoPickSettings_Gem {
            get {
                return ((bool)(this["AutoPickSettings_Gem"]));
            }
            set {
                this["AutoPickSettings_Gem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoPickSettings_Material {
            get {
                return ((bool)(this["AutoPickSettings_Material"]));
            }
            set {
                this["AutoPickSettings_Material"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoPickSettings_Legendary {
            get {
                return ((bool)(this["AutoPickSettings_Legendary"]));
            }
            set {
                this["AutoPickSettings_Legendary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoPickSettings_GreaterRiftKeystone {
            get {
                return ((bool)(this["AutoPickSettings_GreaterRiftKeystone"]));
            }
            set {
                this["AutoPickSettings_GreaterRiftKeystone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoPickSettings_LegendaryAncient {
            get {
                return ((bool)(this["AutoPickSettings_LegendaryAncient"]));
            }
            set {
                this["AutoPickSettings_LegendaryAncient"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int AutoPickSettings_PickupRadius {
            get {
                return ((int)(this["AutoPickSettings_PickupRadius"]));
            }
            set {
                this["AutoPickSettings_PickupRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoPickSettings_Whites {
            get {
                return ((bool)(this["AutoPickSettings_Whites"]));
            }
            set {
                this["AutoPickSettings_Whites"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoPickSettings_Magics {
            get {
                return ((bool)(this["AutoPickSettings_Magics"]));
            }
            set {
                this["AutoPickSettings_Magics"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoPickSettings_Rares {
            get {
                return ((bool)(this["AutoPickSettings_Rares"]));
            }
            set {
                this["AutoPickSettings_Rares"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HotkeyAutoCube_UpgradeRare {
            get {
                return ((string)(this["HotkeyAutoCube_UpgradeRare"]));
            }
            set {
                this["HotkeyAutoCube_UpgradeRare"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HotkeyAutoCube_ConvertMaterial {
            get {
                return ((string)(this["HotkeyAutoCube_ConvertMaterial"]));
            }
            set {
                this["HotkeyAutoCube_ConvertMaterial"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisableAutocastOnNoOverride {
            get {
                return ((bool)(this["DisableAutocastOnNoOverride"]));
            }
            set {
                this["DisableAutocastOnNoOverride"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow (Veiled Crystal) to White (Reusable Parts)")]
        public string ConvertMaterialText {
            get {
                return ((string)(this["ConvertMaterialText"]));
            }
            set {
                this["ConvertMaterialText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rare")]
        public string ConvertMaterialFrom {
            get {
                return ((string)(this["ConvertMaterialFrom"]));
            }
            set {
                this["ConvertMaterialFrom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("normal")]
        public string ConvertMaterialTo {
            get {
                return ((string)(this["ConvertMaterialTo"]));
            }
            set {
                this["ConvertMaterialTo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Overlay_EliteCircles {
            get {
                return ((bool)(this["Overlay_EliteCircles"]));
            }
            set {
                this["Overlay_EliteCircles"] = value;
            }
        }
    }
}
